apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.8.4-openjdk-17-slim
      command:
        - cat
      tty: true
    - name: docker
      image: crimson2022/custom_agent:4
      command:
        - cat
      tty: true
    - name: shell
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: IfNotPresent
      env:
      - name: container
        value: "docker"
      command:
      - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
    volumes:
      - name: docker-config
        configMap:
          name: docker-config # uses worker node permissions
