apiVersion: v1
kind: Pod
spec:
  containers:
    - name: maven
      image: maven:3.8.4-openjdk-17-slim
      command:
        - cat
      tty: true
    - name: docker
      image: crimson2022/custom_agent:2
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
